export { default as AboutSection } from './AboutSection'
export { default as WhoAmISection } from './WhoAmISection'
export { default as WhatIDoSection } from './WhatIDoSection'
export { default as Footer } from './Footer'
export { default as ProjectsSection } from './ProjectsSection'
